// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/account/signup": {
            "post": {
                "description": "Register a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Sign Up",
                "parameters": [
                    {
                        "description": "Sign up credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.req_signUp_successfulRegistration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.res_signUp_successfulRegistration"
                        }
                    },
                    "409": {
                        "description": "Email Already Exist",
                        "schema": {
                            "$ref": "#/definitions/dto.res_signUp_existingEmail"
                        }
                    },
                    "500": {
                        "description": "Failed to hash password / Failed to create user / Failed to generate token",
                        "schema": {
                            "$ref": "#/definitions/dto.res_signUp_failed"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Check if the server is running and healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Server is Healthy",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Server is Healthy"
                },
                "status": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.req_signUp_successfulRegistration": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "country": {
                    "type": "string",
                    "example": "US"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "phone": {
                    "type": "string",
                    "example": "234567890"
                }
            }
        },
        "dto.res_signUp_existingEmail": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Email already registered"
                }
            }
        },
        "dto.res_signUp_failed": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to create user"
                }
            }
        },
        "dto.res_signUp_successfulRegistration": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "User registered successfully"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjU0Mzk4NjMsInVzZXJfaWQiOjE1fQ.aFyEd7PjWTbcBiRRyBoco98fQbU6r3mfNXXPcJhRias"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string",
                            "example": "user@example.com"
                        },
                        "emanameil": {
                            "type": "string",
                            "example": "John Doe"
                        },
                        "uuid": {
                            "type": "string",
                            "example": "d883d46d-7e74-4340-ba36-cf98341d6f4b"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
